Models/Characters.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MyMangaLibrary.Models
{
    public class Characters
    {
        public int ID { get; set; }
        public string Name { get; set; }

        [ForeignKey("MangaID")]
        public int MangaID { get; set; }
        public Manga MangaName { get; set; }
    }
}

Controllers/CharactersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyMangaLibrary.Data;
using MyMangaLibrary.Models;

namespace MyMangaLibrary.Controllers
{
    public class CharactersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CharactersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Characters
        public async Task<IActionResult> Index()
        {
            var ctx = _context.Characters.Include(c => c.MangaName);
            return View(await ctx.ToListAsync());
        }

        public async Task<IActionResult> ShowSearchForm() {
            return View();
        }
        public async Task<IActionResult> ShowSearchResults(string SearchPhrase)
        {
            var ctx = _context.Characters.Include(c => c.MangaName);
            return View("Index", await ctx.Where( m => m.Name.Contains(SearchPhrase)).ToListAsync());
        }
        // GET: Characters/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var characters = await _context.Characters
                .Include(c => c.MangaName)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (characters == null)
            {
                return NotFound();
            }

            return View(characters);
        }

        // GET: Characters/Create
        public IActionResult Create()
        {
            ViewData["MangaID"] = new SelectList(_context.Manga, "ID", "Name");
            return View();
        }

        // POST: Characters/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,MangaID")] Characters characters)
        {
            if (ModelState.IsValid)
            {
                _context.Add(characters);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MangaID"] = new SelectList(_context.Manga, "ID", "Name", characters.MangaID);
            return View(characters);
        }

        // GET: Characters/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var characters = await _context.Characters.FindAsync(id);
            if (characters == null)
            {
                return NotFound();
            }
            ViewData["MangaID"] = new SelectList(_context.Manga, "ID", "Name", characters.MangaID);
            return View(characters);
        }

        // POST: Characters/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,MangaID")] Characters characters)
        {
            if (id != characters.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(characters);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CharactersExists(characters.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MangaID"] = new SelectList(_context.Manga, "ID", "Name", characters.MangaID);
            return View(characters);
        }

        // GET: Characters/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var characters = await _context.Characters
                .Include(c => c.MangaName)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (characters == null)
            {
                return NotFound();
            }

            return View(characters);
        }

        // POST: Characters/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var characters = await _context.Characters.FindAsync(id);
            _context.Characters.Remove(characters);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CharactersExists(int id)
        {
            return _context.Characters.Any(e => e.ID == id);
        }
    }
}

Controllers/MangasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyMangaLibrary.Data;
using MyMangaLibrary.Models;

namespace MyMangaLibrary.Controllers
{
    public class MangasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MangasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Mangas
        public async Task<IActionResult> Index()
        {
            var ctx = _context.Manga.Include(m => m.Mangaka);
            return View(await ctx.ToListAsync());
        }
        public async Task<IActionResult> ShowSearchForm()
        {
            return View();
        }
        public async Task<IActionResult> ShowSearchResults(string SearchPhrase)
        {
            var ctx = _context.Manga.Include(m => m.Mangaka);
            return View("Index", await ctx.Where( m => m.Name.Contains(SearchPhrase)).ToListAsync());
        }
        // GET: Mangas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var manga = await _context.Manga
                .Include(m => m.Mangaka)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (manga == null)
            {
                return NotFound();
            }

            return View(manga);
        }

        // GET: Mangas/Create
        public IActionResult Create()
        {
            ViewData["MangakaID"] = new SelectList(_context.Mangaka, "ID", "Name");
            return View();
        }

        // POST: Mangas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Rating,Name,ChapterCount,MangakaID")] Manga manga)
        {
            if (ModelState.IsValid)
            {
                _context.Add(manga);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MangakaID"] = new SelectList(_context.Mangaka, "ID", "Name", manga.MangakaID);
            return View(manga);
        }

        // GET: Mangas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var manga = await _context.Manga.FindAsync(id);
            if (manga == null)
            {
                return NotFound();
            }
            return View(manga);
        }

        [HttpPost]
        public ActionResult DecreaseChapter(int id) {
            if (id == null) {
                return NotFound();
            }
            var manga =  _context.Manga.Where(m => m.ID == id).FirstOrDefault();
            if (manga == null) {
                return NotFound();
            }

            if (manga.ChapterCount > 0) {
                manga.ChapterCount--;
            } 
            _context.Update(manga);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult IncreaseChapter(int id) {
            if (id == null) {
                return NotFound();
            }
            var manga =  _context.Manga.Where(m => m.ID == id).FirstOrDefault();
            if (manga == null) {
                return NotFound();
            }

            manga.ChapterCount++;
            _context.Update(manga);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        // POST: Mangas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Rating,Name,ChapterCount,Summary")] Manga manga)
        {
            if (id != manga.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(manga);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MangaExists(manga.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(manga);
        }

        // GET: Mangas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var manga = await _context.Manga
                .Include(m => m.Mangaka)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (manga == null)
            {
                return NotFound();
            }

            return View(manga);
        }

        // POST: Mangas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var manga = await _context.Manga.FindAsync(id);
            _context.Manga.Remove(manga);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MangaExists(int id)
        {
            return _context.Manga.Any(e => e.ID == id);
        }
    }
}

Views/Characters/Create.cshtml
@model MyMangaLibrary.Models.Characters

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Characters</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MangaID" class="control-label"></label>
                <select asp-for="MangaID" class ="form-control" asp-items="ViewBag.MangaID"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-dark btn-sm" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Characters/Delete.cshtml
@model MyMangaLibrary.Models.Characters

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Characters</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MangaName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MangaName.Name)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a class="btn btn-dark btn-sm" asp-action="Index">Back to List</a>
    </form>
</div>

Views/Characters/Details.cshtml
@model MyMangaLibrary.Models.Characters

@{
    ViewData["Title"] = "Details";
}
<div>
    <h4>
        @Html.DisplayFor(model => model.Name)
    </h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            Manga
        </dt>
        <dd class = "col-sm-10">
            @Html.ActionLink(@Model.MangaName.Name, "Details", "Mangas", new { id = @Model.MangaID})
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-warning btn-sm" asp-action="Edit" asp-route-id="@Model.ID">Edit</a>
    <a class="btn btn-dark btn-sm" asp-action="Index">Back to List</a>
</div>

Views/Characters/Edit.cshtml
@model MyMangaLibrary.Models.Characters

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Characters</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MangaID" class="control-label"></label>
                <select asp-for="MangaID" class="form-control" asp-items="ViewBag.MangaID"></select>
                <span asp-validation-for="MangaID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-dark btn-sm" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Characters/Index.cshtml
@model IEnumerable<MyMangaLibrary.Models.Characters>

@{
    ViewData["Title"] = "Characters";
}

<h1>Characters</h1>

<p>
    <a class="btn btn-primary btn-sm" asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                Manga
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.ActionLink((string)@item.MangaName.Name, "Details", "Mangas", new { id = @item.MangaID})
            </td>
            <td>
                <a class="btn btn-warning btn-sm" asp-action="Edit" asp-route-id="@item.ID">Edit</a>
                <a class="btn btn-info btn-sm" asp-action="Details" asp-route-id="@item.ID">Details</a>
                <a class="btn btn-danger btn-sm" asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
<pre>
This section is for creating an characters

 <p style="color:red;">Disclaimer:You can't create characreter witouth creating manga</p>
</pre>

Views/Characters/ShowSearchForm.cshtml
<h1>Search Characters</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="ShowSearchResults">
            <div class="form-group">
                <label for="SearchPhrase" class="control-label"></label>
                <input name="SearchPhrase" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-dark btn-sm" asp-action="Index">Back to List</a>
</div>